### ISSUE TITLE
[BUG]list页面不显示响应

### ISSUE THREAD

**Issue by Qiuyebai-1226** [iiop123/dingding#3]
![QQ截图20221216133453](https://user-images.githubusercontent.com/62199231/208029803-14a62ac7-dc7f-4d64-af37-038b31162657.png)
如图，输入密码后返回响应，但是页面没有显示

**Comment by iiop123** [comment]
应该是后台只有一个文件的问题

**Comment by Qiuyebai-1226** [comment]
试了下，还真是，算是个小bug蛤蛤蛤

**Comment by iiop123** [comment]
已修复
